language: java
addons:
  apt:
    packages:
    - mediainfo 
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7    
#install: mvn external:install 
script: mvn install -Dmaven.javadoc.skip=true -B -V -DskipTests=true

branches:
  only:
    - dev
