language: java

cache:
  directories:
  - $HOME/.m2

addons:
  apt:
    packages:
    - mediainfo 

matrix:
  include:
    - os: linux
      jdk: openjdk7
    - os: linux
      dist: precise
      jdk: oraclejdk7
    - os: linux
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: openjdk8
    - os: osx

before_install: echo "MAVEN_OPTS='-XX:+TieredCompilation -XX:TieredStopAtLevel=1'" > ~/.mavenrc

install: mvn external:install 

script: mvn verify -B -V
