language: java

cache:
  directories:
    $HOME/.m2

addons:
  apt:
    packages:
    - mediainfo 

matrix:
  include:
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: openjdk8
    - os: osx
      osx_image: xcode9.2

script: mvn verify -B -V

notifications:
  email: false
